version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 254805
      POSTGRES_DB: go_lang
    ports:
      - "5432:5432"
